---
title: "Visualizing Police-Public Contact and Crime Victimization"
author: "Mandi Acevedo and Bela Walkin"
format: html
self-contained: true
editor: visual
---

```{r}
library(haven)
PPCS <- read_dta("PPCS.dta")
library(tidyverse)
```

# Visualization 1

```{r}

PPCS |>
  mutate(as.numeric(ARRESTED)) |>
  filter(ARRESTED == 1) |>
  ggplot(aes(x = EDUCATION_SUB)) +
  geom_histogram(binwidth=1,
                 fill = "pink",
                 color = "black") +
  scale_x_continuous(breaks = seq(0, 18, 1)) +
  theme_minimal() + 
  labs(title = paste0("Of survey respondents who have been arrested, most have 
no more than a high school level education."),
      subtitle = "Includes responses from 2002, 2008, 2011",
      caption = "Source: Police-Public Contact Survey and National Crime Victimization Survey, Accessed Through ICPSR", 
      x = "Years of Education",
      y = "Number of Respondents")
```

# Visualization 2

```{r}

PPCS |>
  filter(NUM_CONT < 75) |>
  ggplot() +
  geom_point(aes(x = NUM_MOVES,
                 y = NUM_CONT),
             alpha = 0.1,
             color = "pink") +
  geom_smooth(mapping = aes(x = NUM_MOVES,
                            y = NUM_CONT),
              method = "lm",
              se = FALSE,
              color = "black") +
  scale_x_continuous(breaks = seq(0, 75, 5)) +
  theme_minimal() +
  labs(title = paste("Frequent moving is asociated with more police contacts."),
       subtitle = "Survey Respondents from 2002, 2008, 2011",
       caption = paste("Source: Police-Public Contact Survey and", 
"National Crime Victimization Survey, Accessed Through ICPSR"),
       x = "Number of times moved in the last 5 years",
       y = "Amount of police contacts in past 12 months")
```

# Visualization 3

```{r}
PPCS |>
  mutate(TOTAL_VALUE_LOSS = VAL_LOSS2_INC_P23HH + VAL_LOSS2_INC_P23PER) |>
  mutate(MSA_STATUS = case_when(
    MSA_STATUS == 1 ~ "Urban",
    MSA_STATUS == 2 ~ "Suburban",
    MSA_STATUS == 3 ~ "Rural")) |>
  ggplot(aes(
    x = factor(MSA_STATUS), 
    y = TOTAL_VALUE_LOSS))+
  geom_boxplot(outlier.shape = NA,
               fill = "pink",
               color = "black")+
  scale_y_continuous(limits = c(0,750)) +
  theme_minimal()+
  labs(title = "Stolen property values are, on average, highest amongst suburban victims.",
         subtitle = paste("Distribution of reported value of cash/property lost",
         "by Metropolitan Statistical Area (MSA) type"),
         caption = "Source: Police-Public Contact Survey and National Crime Victimization Survey, Accessed through ICPSR",
         x = "MSA type",
         y = "Total value of cash & property lost (USD)")

```
